# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
