# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20170323_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=40)),
                ('admission_date', models.DateField()),
                ('passout_date', models.DateField()),
                ('current_organization_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('work_phone', models.CharField(max_length=12)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('active_flag', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('active_flag', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=40)),
                ('admission_date', models.DateField()),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('active_flag', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
