# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_opportunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='opportunity_info',
            field=models.TextField(max_length=1000),
        ),
    ]
