# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_auto_20170327_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunities',
            name='expiration_data',
        ),
        migrations.AddField(
            model_name='opportunities',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
