# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0012_auto_20170328_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_dp',
            field=models.FileField(default='def.jpg', upload_to=b''),
        ),
    ]
