# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0014_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_category',
            field=models.CharField(choices=[('technical', 'technical'), ('financial', 'financial'), ('academic', 'academic'), ('other', 'other')], default='technical', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
