# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0015_auto_20170403_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_category',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('academic', 'Academic'), ('other', 'Other')], default='technical', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
